name: DockerHub
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/docker_hub.yml'
      - '.github/workflows/validate.yml'
      - '**/Dockerfile'
      - 'Dockerfile'
      - 'entrypoint.sh'
      - 'versions.json'
  schedule:
    - cron: 0 21 * * 0
env:
  DOCKER_USER: 41772ki
  DOCKER_REPO: danger-swiftlint
jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          matrix=$(cat versions.json | jq -c .)
          echo "::set-output name=matrix::$matrix"
  build:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: 
        swift_version: ${{ fromJson(needs.generate-matrix.outputs.matrix).swift_version }}
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.head_ref }}-${{ github.workflow }}-${{ matrix.swift_version }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
    - id: set-swiftlint-version
      name: Set SwiftLint Version
      run: |
        swiftlint_version=$(echo '${{ needs.generate-matrix.outputs.matrix }}' | jq -c '.swiftlint_supported_version' | jq -r '.["${{ matrix.swift_version }}"]')
        echo "::set-output name=swiftlint-version::$swiftlint_version"
    - name: Login DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Create tags for push
      id: create-tags
      run: |
        if [ "${{ matrix.swift_version }}" == 'latest' ]; then
          SWIFT_VERSION=latest BASE_IMAGE=$(eval "echo \"$(cat Dockerfile | grep FROM | awk '{ print $NF }')\"")
          docker pull $BASE_IMAGE
          SWIFT_VERSION=$(docker run --entrypoint swift "$BASE_IMAGE" --version | grep 'Swift version' | awk '{ print $NF }' | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')
          SWIFT_VERSION_MAJOR_MINOR=$(echo $SWIFT_VERSION | sed -E 's/([0-9]*)\.([0-9]*)(\.([0-9]*))?/\1.\2/g')
          SWIFT_VERSION_MAJOR=$(echo $SWIFT_VERSION | sed -E 's/([0-9]*)\.([0-9]*)(\.([0-9]*))?/\1/g')
          TAGS=$(echo "[\"latest\", \"$SWIFT_VERSION\", \"$SWIFT_VERSION_MAJOR_MINOR\",\"$SWIFT_VERSION_MAJOR\"]" | jq -r '. | unique | map("${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:" + .) | join(",")')
          echo "::set-output name=tags::$TAGS"
        else
          echo "::set-output name=tags::${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:${{ matrix.swift_version }}"
        fi
    - name: Build Docker image and push to DockerHub
      uses: docker/build-push-action@v2
      with: 
        push: true
        tags: ${{ steps.create-tags.outputs.tags }}
        build-args: |
          SWIFT_VERSION=${{ matrix.swift_version }}
          SWIFT_LINT_REVISION=${{ steps.set-swiftlint-version.outputs.swiftlint-version }}
    - name: Print Versions
      run: docker run --entrypoint show-versions "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}"
    # - name: Update readme on DockerHub
    #   uses: wei/curl@v1
    #   with:
    #     args: -X POST ${{ secrets.DOCKER_HUB_TRIGGER_URL }}
