name: DockerHub
on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/docker_hub.yml'
      - '.github/workflows/validate.yml'
      - '**/Dockerfile'
  schedule:
    - cron: 0 21 * * 0
env:
  DOCKER_USER: 41772ki
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_REPO: danger-swiftlint
jobs:
  build:
    strategy:
      matrix:
        swift_version: [latest, 5.1.3, 5.1.2, 5.1.1]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: docker build -t "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" --build-arg "SWIFT_VERSION=${{ matrix.swift_version }}" .
    - name: Validate Swift
      run: docker run --entrypoint swift "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" --version
    - name: Validate Danger-Swift
      run: docker run "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" --version
    - name: Validate Danger-JS
      run: docker run --entrypoint danger "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" --version
    - name: Validate SwiftLint
      run: docker run --entrypoint swiftlint "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" version
    - name: Login DockerHub
      run: echo "${DOCKER_PASS}" | docker login -u ${DOCKER_USER} --password-stdin
    - name: Push DockerHub
      run: |
        IMAGE_NAME=$(docker images "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" -q)
        SWIFT_VERSION=$(docker run --entrypoint swift "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" --version | grep 'Swift version' | awk '{ print $NF }' | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')
        scripts/docker_push_tag.sh "$IMAGE_NAME" "${DOCKER_USER}/${DOCKER_REPO}" "$SWIFT_VERSION"

        if [ "${{ matrix.swift_version }}" == 'latest' ]; then
          scripts/docker_push_tag.sh "$IMAGE_NAME" "${DOCKER_USER}/${DOCKER_REPO}" "latest"

          SWIFT_VERSION_MAJOR_MINOR=$(echo $SWIFT_VERSION | sed -E 's/([0-9]*)\.([0-9]*)\.([0-9]*)/\1.\2/g')
          scripts/docker_push_tag.sh "$IMAGE_NAME" "${DOCKER_USER}/${DOCKER_REPO}" "$SWIFT_VERSION_MAJOR_MINOR"

          SWIFT_VERSION_MAJOR=$(echo $SWIFT_VERSION | sed -E 's/([0-9]*)\.([0-9]*)\.([0-9]*)/\1/g')
          scripts/docker_push_tag.sh "$IMAGE_NAME" "${DOCKER_USER}/${DOCKER_REPO}" "$SWIFT_VERSION_MAJOR"
        fi
    - name: Update readme on DockerHub
      uses: wei/curl@v1
      with:
        args: -X POST ${{ secrets.DOCKER_HUB_TRIGGER_URL }}
