name: Validate Dockerfile
on: 
  pull_request:
    paths:
      - '.github/workflows/docker_hub.yml'
      - '.github/workflows/validate.yml'
      - '**/Dockerfile'
env:
  DOCKER_USER: 41772ki
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_REPO: danger-swiftlint
jobs:
  validate:
    strategy:
      matrix:
        swift_version: [latest, 5.1.3, 5.1.2, 5.1.1]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: docker build -t "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" --build-arg "SWIFT_VERSION=${{ matrix.swift_version }}" .
    - name: Print Versions
      run: docker run --entrypoint show-versions "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}"
    - name: Run with sample Dangerfile.swift
      run: docker run "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}"
